### ISSUE TITLE
Incorrect translation of an insertion mutation

### ISSUE THREAD

**Issue by gilhornung** [ambj/MuPeXI#10]
Hi Anne-Mette,

I noticed a case in which MuPeXI placed an insertion in the wrong place, and caused the wrong amino acid to appear in a peptide.

As you can see in the IGV snapshot below, there is an insertion of a C in the sequence AGAGG, just after the AGA. This leads to the codons [AGA][**C**GG] which translates to amino acid sequence RR. However, MupeXI translated this sequence as RA, suggesting that the mutated sequence is [AGA][G**C**G]

You can find all the relevant files (vcf, vep and mupexi) in the link:
https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/CzZS5bh53pHTxPP

![net1_bug](https://user-images.githubusercontent.com/25452585/38031502-f9123518-32a3-11e8-82f3-f662ec396a4c.png)

All the best,

Gil

**Comment by ambj** [comment]
Hi Gil

Thank you very much for pointing this out and providing the necessary data to test and solve the problem. I will look into this as soon as possible! 
(also - i have not forgotten your previous bug-report - I will find a week and go into code-mode to fix all bugs reported)

Best, 
AM

**Comment by ambj** [comment]
Hi @gilhornung 
Can i get you to state the whole peptide or vcf entry that are causing this problem? 
Best, 
/AM

**Comment by gilhornung** [comment]
In the vcf `wexome_curated.vcf` in the link in the first message of the issue. The position is CHROM=10 POS=5454288

**Comment by ambj** [comment]
@gilhornung 

It is now corrected and updated on the dev branch
Merging into master when releasing the new version 

/AM

**Comment by ambj** [comment]
fixed in version 1.2.0
