### ISSUE TITLE
Transition to NetMHCpan 4.0 is not documented

### ISSUE THREAD

**Issue by gilhornung** [ambj/MuPeXI#11]
Hi Anne-Mette,

I'm trying to work with the latest MuPeXI version (1.2)

I noticed that you started working with NetMHCpan 4, but the README and the config.ini file still reference  to NetMHCpan 3.0.

Gil

**Comment by ambj** [comment]
Hi Gil 
Thank you for noticing this - i will update the two files ASAP 
Best, 
/AM

**Comment by ambj** [comment]
Now updated on master branch
