### ISSUE TITLE
broken link for test.vcf and expression_test.vcf

### ISSUE THREAD

**Issue by trishorts** [ambj/MuPeXI#13]
I'm trying to test installation using the test files described on you main page. But, the links to those files don't work. Would you check into this for me please?

**Comment by ambj** [comment]
The example file links and the rest of det [user manuel](https://github.com/ambj/MuPeXI/blob/master/doc/MuPeXI_User_Manual.md)  have now been updated.
Sorry for the inconvenience.

Best, 
/AM

**Comment by trishorts** [comment]
No problem. I'm quite excited to get this working. It's a struggle because I'm not really strong in python/perl/linux. Getting everything up and running is a real challenge. I'm fortunate to have some folks around to help.  

I wonder if you need to specify which version of VEP you are supporting. The latest is 92, and that did not work right away. I had to get someone to reprogram part of your code to get that to go through. Earlier versions of VEP working sort-of. The one you showed originally before your update (85, I think) isn't even available anymore. I tried 87 and that was ok.

**Comment by ambj** [comment]
The latest i have tested is 87. 
Can you describe what is not working between MuPeXI and VEP and what you coworker reprogrammed? Otherwise i will not be able to solve this problem for other users.  
And also please provide the error message from the MuPeXI run.

**Comment by trishorts** [comment]
I think I might have misspoke a little. This is the message I got. I can give you more when he gets in.

I worked a little more on getting MuPeXI to work on your computer.
1.	Your cache for VEP is at /home/SSS/.vep -- I tried installing version 87 of the cache, but that failed due to the script named something like convert_cache.py
2.	I got VEP working with version 92 of the cache, which you had already downloaded
3.	MuPeXI still reported "cannot detect format," which was annoying because it's clearly a VCF file. 
4.	I edited the MuPeXI script (saved as MuPeXi_ajc.py) to bypass that with the `--format vcf` option for VEP.
5.	I also bypassed the routine in MuPeXI.py to make the VCF "vep_compatible" because it was just outputting the header and no other lines, which was useless.
6.	It ran VEP successfully and seemed to process the VEP output successfully
7.	It's now failing at the NetMHC step, due to some assertion within the MuPeXI.py script.

**Comment by ambj** [comment]
Ok it seems that there might be some incompatibilities between the Ensembl VEP versions. 
Can i get you to make a new issue concerning this, and provide me with a test vcf file cousing the problem and the versions of the Ensembl VEP you see the error and which you do not. also please post the MuPeXI error message. 

I will close this issue now as the title of the issue have been solved.
