### ISSUE TITLE
Variant Effect Predictor version compatibility 

### ISSUE THREAD

**Issue by trishorts** [ambj/MuPeXI#14]
latest version of VEP as of 05/01/2018 is 92. No version requirement is stated on the main MuPeXI git page. MuPeXI doesn't seem immediately compatible with this to start with as the program variant_effect_predictor.pl has been renamed to vep (plus other changes)

In the MuPeXI user manual shows usage of version 85.
![image](https://user-images.githubusercontent.com/16841846/39475694-d7dac8d4-4d1e-11e8-84a4-7d246c92294e.png)

However, this version is no longer available.

Version 87 could possibly work but there are (I believe) 27 releases (87.0-87.27). Not sure if that level matters. 

What would help the most would be specification of which latest version is known to function well.

**Comment by ambj** [comment]
Ensembls  VEP version 87 works. 

I will test MuPeXI with one of the newest versions. 

Best, 
/AM

**Comment by isidroc** [comment]
Any updates on this thread? Thanks

**Comment by ambj** [comment]
Hi 
Unfortunately I havn't had time to look into this issue the latest version of VEP i have tested is 87. 
Thank you for reminding me of this issue - hopefully i have time to test the latest version installed on our HPC during November. 
Best, 
/AM

**Comment by 2236529177** [comment]
is release 95 ok @ambj

**Comment by ambj** [comment]
Unfortunately i dont this it will as VEP have changed the general setup and how to run the program since version 90.

**Comment by 2236529177** [comment]
@ambj god, you are here, I am urgent for your help. no version of vep has the variant_effect_predictor.pl  and variant_effect_predictor, what should i do, help, **really very urgent**.
[image](https://user-images.githubusercontent.com/25199946/51104193-5ecca200-1820-11e9-91b3-6537a810ebca.png)
![image](https://user-images.githubusercontent.com/25199946/51104212-74da6280-1820-11e9-8a2b-67ced50a04a7.png)


from the issue, I  know you said you have tested ensemble_87, so I tried to keep the same with you, but I do not have 
fasta = /your/path/to/references/human_GRCh38/GCA_000001405.15_GRCh38_full_analysis_set.fa
chain = /your/path/to/references/human_GRCh37/liftover/hg19ToHg38.over.chain
cDNA = /your/path/to/references/human_GRCh38/cDNA/Homo_sapiens.GRCh38.85.cdna.all.fa
pep = /your/path/to/references/human_GRCh38/pep/Homo_sapiens.GRCh38.85.pep.all.fa
cosmic = /your/path/to/references/cosmic/Census_allWed_Feb_17_09-33-40_2016.tsv

I tried to download the corresponding file, but I am afraid I am wrong. so I am here to confrim with you.
http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz **for chain**
what is worse, there are several files in ensemble_87, which file should I choose in fastq pep cdna. I list the link here, hope you can point out for me.

the worsest thing is that  I know cosmic vcf file, but never use cosmic tsv file, so can you tell me where to download.

ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/pep/
ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/cdna/
ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/dna/.

I send some emails to your eamil ambj@cbs.dtu.dk, I do not whether there is some bug in your school`s email, many days no reply.

I know my questions will waste you much time, sorry for disturb. wish you publish more CNS paper.

**Comment by 2236529177** [comment]
dear amnj,  why you delete my comment, how should I do, very urgent, thanks a lot

**Comment by ambj** [comment]
To keep this thread clean - I moved it to a now issue see #23

**Comment by 2236529177** [comment]
@trishorts have you solved your problem? thanks

**Comment by 2236529177** [comment]
> I moved on.
@trishorts 
thanks a lot. is it convenient for you to give an email,

**Comment by ambj** [comment]
Dear @trishorts and @isidroc 

I have now tested MuPeXI with the lates version of VEP (95.1). 

Nothing have changed in the way you run VEP and therefore how MuPeXI calls the command. VEP have changed how they build the tool and isolated VEP from the ensembl-tools-release. If you follow the installation instructions provided by Ensembl (https://www.ensembl.org/info/docs/tools/vep/script/index.html) you will end up with an executable where you just need to call fx "vep --help" when it is loaded in your PATH. 

MuPeXI is able to use both the short executable or the full path but either should still be stated in the config.ini file 

Sorry for the late respons - hope you found a way out of the problem. 

Best, 
Anne-Mette
