### ISSUE TITLE
What does an error message mean?

### ISSUE THREAD

**Issue by hsun9** [ambj/MuPeXI#15]
python ../../software/MuPeXI/MuPeXI.py -v data/example.vcf -a HLA-A01:01,HLA-B08:01 -c ../../software/MuPeXI/config.ini -e data/example_expression.tsv

Reading in data
	Creating expression file dictionary
	Creating proteome reference dictionary
	Creating genome reference dictionary
	Creating cancer genes list

VEP: Starting process for running the Ensembl Variant Effect Predictor
	Detecting variant caller
		MuTect2
	Change VCF to the VEP compatible
	Extracting allele frequencies
	Running VEP
	Creating mutation information dictionary

MuPeX: Starting mutant peptide extraction
	Extracting all possible peptides from reference
		Peptides of 9 aa are being extracted
	Peptide extraction begun
		Running 9 aa normal peptide match
Traceback (most recent call last):
  File "../../software/MuPeXI/MuPeXI.py", line 1785, in <module>
    main(sys.argv[1:])
  File "../../software/MuPeXI/MuPeXI.py", line 78, in main
    peptide_info, peptide_counters, fasta_printout, pepmatch_file_names = peptide_extraction(peptide_length, vep_info, proteome_reference, genome_reference, reference_peptides, reference_peptide_file_names, input_.fasta_file_name, paths.peptide_match, tmp_dir, input_.webserver, input_.print_mismatch, input_.keep_temp, input_.prefix, input_.outdir, input_.num_mismatches)
  File "../../software/MuPeXI/MuPeXI.py", line 729, in peptide_extraction
    peptide_info, pepmatch_file_names = normal_peptide_correction(mutated_peptides_missing_normal, mutation_info, p_length, reference_peptide_file_names, peptide_info, peptide_match, tmp_dir, pepmatch_file_names, webserver, print_mismatch, num_mismatches)
  File "../../software/MuPeXI/MuPeXI.py", line 949, in normal_peptide_correction
    pepmatch_file = run_peptide_match(mutpeps_file, peptide_length, peptide_match, reference_peptide_file_names, mutation_info, tmp_dir, webserver, print_mismatch, num_mismatches)
  File "../../software/MuPeXI/MuPeXI.py", line 974, in run_peptide_match
    process_pepmatch = subprocess.Popen([peptide_match, '-thr' , str(num_mismatches), mutpeps_file.name, reference_peptide_file_name], stdout = pepmatch_file)
  File "/gscmnt/gc2737/ding/hsun/software/miniconda2/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/gscmnt/gc2737/ding/hsun/software/miniconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by ambj** [comment]
You dont have permission to read or execute the file. This is most likely the pepmatch program in the /bin dir. 
check if this is both readable and executable, if not change this on the commandline with the chmod command.

**Comment by hsun9** [comment]
All of python library files are executable. However, the problem has not solved. 
I wonder if the python code need to change. 
https://stackoverflow.com/questions/44151470/oserror-errno-13-permission-denied-with-subprocess-check-output

**Comment by hsun9** [comment]
Thanks. I send the files to you by email.

**Comment by ambj** [comment]
Dear Sun 

You have sent me my own test files, as these work on my system i cannot reproduce your error and it therefor emphasize's that the error occurs on your local system. 
I would double check this you have permission to run all the dependencies and the the paths are stated correctly in the config.ini file. 

Best, 
Anne-Mette

**Comment by hsun9** [comment]
I sent your own test files to you because I only ran MuPeXI using the files.
Thank you for your time and response.
Now, I know the problem may be in my system.

Best,
Hua

**Comment by sa256** [comment]
Hello Hua, 

I am running into the same problem. Could you solve it and could you share the solution here?

Regards
Anchal

**Comment by hsun9** [comment]
Hi Anchal,

My previous problem was the Python problem. So, the problem was solved after installing `conda install -c anaconda python-dateutil=v2.7.3`. 

I hope it may be helpful.

Best,
Hua
