### ISSUE TITLE
ERROR VEP output file empty

### ISSUE THREAD

**Issue by LeeNicha** [ambj/MuPeXI#19]
Hi, I got an error after I type this command
$python MuPeXI.py -v ../Variant_calling/Strelka2_result/case1.strelka.snvs.vcf -a HLA-A02:01 -o case1_strelka -s human -c config.ini

**ERROR**:
Reading in data
	Creating proteome reference dictionary
	Creating genome reference dictionary
	Creating cancer genes list

VEP: Starting process for running the Ensembl Variant Effect Predictor
	Detecting variant caller
		Variant caller not detected in VCF file.
		NOTE:	Genomic allele frequency is only taken into account
			with variant calls from MuTect or MuTect2!
	Change VCF to the VEP compatible
	Extracting allele frequencies
	Running VEP
ERROR: VEP output file empty
VEP 
-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/onnicha/Thesis/ensembl-vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/onnicha/Thesis/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/onnicha/Thesis/ensembl-vep/vep:224
Date (localtime)    = Wed Aug 15 23:50:23 2018
Ensembl API version = 93
---------------------------------------------------
Thanks

**Comment by ambj** [comment]
This error is concerning the VEP installation. VEP is not able to find the offline cache of the reference. The path should be stated in the config.ini file
