### ISSUE TITLE
surprising Permission denied

### ISSUE THREAD

**Issue by kobejamescurry** [ambj/MuPeXI#24]
dear professor,
thanks for your hard work in this software. I get some errors beyond my ability after trying many times.
I used ensemble_87, netMHCpan4.0, python2.7.

here is my command, /public/software/python2.7.15/bin/python2.7 MuPeXI.py -v /public/software/hla/MuPeXI/result_first/example.vcf -a HLA-A01:01,HLA-B08:01 -c /public/software/hla/MuPeXI/config.ini  -l 8-12 -A GRCh37 -F 10 -d /public/software/hla/MuPeXI/result_first -o first_test.mupexi -L first_test.g -f -t.
.
but the result is much different from what in the web_browser, for example, it lacks some columns, like affnity.
what is more, the directory for chop peptide in my config.ini is still empty,

can you help me?
![image](https://user-images.githubusercontent.com/46668881/51387816-6d89c080-1b62-11e9-8f5f-cb5b16a2fbf8.png)

![image](https://user-images.githubusercontent.com/46668881/51387899-be011e00-1b62-11e9-95df-55a9c4de2833.png)

![image](https://user-images.githubusercontent.com/46668881/51387906-c6f1ef80-1b62-11e9-8d80-46f9275a231c.png)

**Comment by ambj** [comment]
Dear ? 
you have made fill permission to the input file - since the program run the first half this is not where the permission error occurs.  
Have you looked at your permission to NetMHCpan 4.0? Since you are running with the print temp file option (-t) it looks like the input file to netMHCpan is generated but not the output files. have you stated the correct path in the config.ini file? 
Best, 
Anne-Mette

**Comment by kobejamescurry** [comment]
I have test NetMHCpan 4.0 singly acoording to the guide as the png shows.
why I use -t, because I want to get the short peptide file if I want to use other software, like mhcflurry to predict the affnity, but I do not know which argument will finally get this, so I guess argument -t may has this function.

![image](https://user-images.githubusercontent.com/25199946/51385729-16342200-1b5b-11e9-8736-b8f9445e5a41.png)

following is my config.ini. and I have a doubt about liftover, If I just want hg19, still need to liftover, I think not, but in the config.ini comment ,you said " [LiftOver] # Optional, only necessary when using the GRCh37 genome reference,", can you help me to confirm this, thanks a lot.


## This configuration file points to programs and reference files used by MuPeXI.
## The file is structured so groups are stated in [] and names underneath folowed by =.
## You should ONLY change the path to your references, not the groups nor the names. 

[netMHC]
# Please specify the NetMHCpan binary path
MHC = /public/software/hla/netMHCpan-4.0

[EnsemblVEP]
# Please specify path to the Ensembl Variant effect predictor (VEP) binary, and the 
# directory containing the cache database. 
# The VEPdir is the directory containing the cached references. (human/GRCh38)
VEP = /public/software/old_vep/ensembl-vep/vep.pl
VEPdir = /public/software/old_vep/ensembl-vep/

[References]
# Please specify the path to the reference files 
# NOTE: The individual peptide reference files (pep8 etc.) are generated by MuPeXI in the
# first run, and can be obtained and saved by keeping temporary files (-t option)  
cDNA = /public/software/old_vep/ensembl-vep/reference/cdna/Homo_sapiens.GRCh37.cdna.all.fa
pep = /public/software/old_vep/ensembl-vep/reference/pep/Homo_sapiens.GRCh37.pep.all.fa
cosmic = /public/software/old_vep/ensembl-vep/reference/Census_allFriJan_18_02_55_51_2019.tsv
pep8 = /public/software/hla/MuPeXI/tmp_chop_pep/reference_peptide_8.txt
pep9 = /public/software/hla/MuPeXI/tmp_chop_pep/reference_peptide_9.txt
pep10 = /public/software/hla/MuPeXI/tmp_chop_pep/reference_peptide_10.txt
pep11 = /public/software/hla/MuPeXI/tmp_chop_pep/reference_peptide_11.txt
pep12 = /public/software/hla/MuPeXI/tmp_chop_pep/reference_peptide_12.txt

[PeptideMatch]
# Please specify the path to the pepmatch binary file matching your operating system
PM = /public/software/hla/MuPeXI/bin/pepmatch_db_x86_64

[LiftOver]
# Optional, only necessary when using the GRCh37 genome reference,
# since we just need hg19, we does not make convert
fasta = /your/path/to/references/human_GRCh38/GCA_000001405.15_GRCh38_full_analysis_set.fa
chain = /public/software/old_vep/ensembl-vep/hg19ToHg38.over.chain
java8 = /public/software/jdk1.8.0_202/bin/java
picard = /public/software/picard.jar

**Comment by ambj** [comment]
HG19 is the same as GRCh37. 
If you are not using GRCh38 you need to liftover your vcf file from GRCh37 to GRCh38. 
you need to make sure that the functioning path to NetMHCpan is stated correctly in the config.ini file. 
Best, 
/AM

**Comment by kobejamescurry** [comment]
thanks a lot 
**MHC = /public/software/hla/netMHCpan-4.0**   is my  functioning path to NetMHCpan , in the above png I have show that it is ok to run, or should I give you more pngs , if needed, I will post here , thanks a lot




I post my config.ini here again.

![qq 20190118201514](https://user-images.githubusercontent.com/46668881/51386551-cf93f700-1b5d-11e9-8553-5a8709741a76.png)

**Comment by kobejamescurry** [comment]
and according to the manual, it seems that, for each progect, I need to make the peptide file(pep8, pep9,pep10,pep11,pep12), is there more easy way to this? thanks a lot

**Comment by kobejamescurry** [comment]
> Dear ?
> You have made full permission to the input file - since the program runs the first half this is not where the permission error occurs.
> Have you looked at your permission to NetMHCpan 4.0? Since you are running with the print temp file option (-t) it looks like the input file to netMHCpan is generated but not the output files. have you stated the correct path in the config.ini file?
> Best,
> Anne-Mette
ater your help, finally it can run, thanks a lot
but he result seems different, I change my question, when you are not that busy, hope you can give me some instrctions, thanks a lot

**Comment by kobejamescurry** [comment]
the red four columns disappeared, thanks a lot
![image](https://user-images.githubusercontent.com/46668881/51388204-a6766500-1b63-11e9-83a9-2f0f743aa2d9.png)

**Comment by ambj** [comment]
Dear ? 
It is difficult for me to help you when you change or edit your original question. 
It is not clear to me what you problem is now - dod you succeed with the permission error? 
Best, 
Anne-Mette

**Comment by kobejamescurry** [comment]
> Dear ?
> It is difficult for me to help you when you change or edit your original question.
> It is not clear to me what you problem is now - did you succeed with the permission error?
> Best,
> Anne-Mette

yes, it is ok now, but the excel result I showed you is different from webbrowser, the column names is different, lack foru columns.

and what is more, the directory for chop peptide in my config.ini is still empty, i mean pep8, pep9 pep10 in config.ini, thanks a lot

**Comment by ambj** [comment]
Yes the output change when you use the full netMHCpan run - getting both the eluted ligand rank score output and the binding affinity output. unfortunately i have not change the explanation for this in user manual yet. 

The references you are referring to are not necessary to be stated in the config.ini file. they are generated for each run if not stated there - you can save a bit of processing time by using the -t option to get them printed and then save then and state the paths in the config.ini file.

**Comment by ambj** [comment]
I kindly refer to reading the MuPeXI paper, user manual and NetMHCpan paper i detail - this does not seem to be an issue with the software.

**Comment by kobejamescurry** [comment]
> I kindly refer to reading the MuPeXI paper, user manual and NetMHCpan paper i detail - this does not seem to be an issue with the software.

I have read that, haha, thanks a lot, can you give me some help, I have achived a lot. just the last step, if you are free, give me some help, very much thanks
