### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Phorutai** [ambj/MuPeXI#7]
Hi,
I run MuPeXI with VCF file called from mutect2, but I got this error 

MuPeI: Starting mutant peptide informer
	Writing temporary peptide file
	Running NetMHCpan
	Creating NetMHCpan file dictionary
Traceback (most recent call last):
  File "/apps/MuPeXI/MuPeXI.py", line 1637, in <module>
    main(sys.argv[1:])
  File "/apps/MuPeXI/MuPeXI.py", line 98, in main
    net_mhc = build_netMHC(netMHC_file, input_.webserver)
  File "/apps/MuPeXI/MuPeXI.py", line 1092, in build_netMHC
    rank = float(line[13])
IndexError: list index out of range

How should I fix this problem?

**Comment by Phorutai** [comment]
Even if I tried to run your example file, I got the same error.

**Comment by ambj** [comment]
Which version of NetMHCpan and MuPeXI er you running? 
It looks like you are trying to run NetMHCpan4.0 with MuPeXI 1.1.3. 
MuPeXI have been updated in the development (dev) branch to work with NetMHCpan 4.0 the new MePeXI version will soon be merged into the master branch, until then you can clone the dev branch. 

Best,
/AM

**Comment by ambj** [comment]
Which version of NetMHCpan and MuPeXI er you running?
It looks like you are trying to run NetMHCpan4.0 with MuPeXI 1.1.3.
MuPeXI have been updated in the dev branch to work with NetMHCpan 4.0 the new MePeXI version will soon be merges into the master branch, until then you can clone the dev branch.

Best,
/AM

On Mar 20, 2018, at 10:44, Phorutai <notifications@github.com<mailto:notifications@github.com>> wrote:


Even if I tried to run your example file, I got the same error.

**Comment by Phorutai** [comment]
Thank you for a quick reply. 
Yes, I used  NetMHCpan4.0, I will try with the new version, but actually if I use  NetMHCpan3.0 instead, would it be ok?

Best,
Phorutai

**Comment by ambj** [comment]
Yes it should work with 3.0
