### ISSUE TITLE
error about vep output file empty 

### ISSUE THREAD

**Issue by huangxiaogua** [ambj/MuPeXI#8]
hello, when i run the sample data , the commad as follows: pyhton MuPeXI.py -v home/jm/mupexi/data/example.vcf -a HLA-A01:01 -e expression.tsv -l 9 -c home/jm/mupexi/config.ini -o home/jm/mupexi/data/output
had the error about vep output file empty. can not use transcript reference sequences(--use_transcript_ref) without a FASTA file (see --fasta); you may wish to use --use_given_ref
Vep can run normally alone. can you tell me what's the possible reasons. Thank you!

**Comment by ambj** [comment]
Can you post the error message? 
Best, 
Anne-Mette
