### ISSUE TITLE
long FASTA output

### ISSUE THREAD

**Issue by Phorutai** [ambj/MuPeXI#9]
Hi,
I have a question about the FASTA output from MuPeXI web server. I wonder that the FASTA lists contain only peptides from the prediction with HLA that I input or contain all non-synonymous mutations from input VCF file?

Best,
Phorutai

**Comment by ambj** [comment]
Hi Phorutai
The FASTA output file is not relying on the HLA alleles. This is an additional output file stating the long peptides, originating from the mutations in the input VCF file, stretching all possible minimal peptides of the user defined length(s).

Best, 
AM

**Comment by Phorutai** [comment]
Thank you very much, it is very useful.

Best,
Phorutai
